name: Build Mod Menu

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Theos & SDKs
      run: |
        git clone --recursive https://github.com/theos/theos.git ~/theos
        echo "THEOS=~/theos" >> $GITHUB_ENV
        
        # Var olan boş sdks klasörünü silip güncel SDK'ları yüklüyoruz
        rm -rf ~/theos/sdks
        git clone --depth=1 https://github.com/theos/sdks.git ~/theos/sdks

    - name: Find Makefile and Build
      run: |
        export THEOS=~/theos
        
        MAKE_DIR=$(find . -maxdepth 3 -name "Makefile" -exec dirname {} \; | head -n 1)
        
        if [ -n "$MAKE_DIR" ]; then
          cd "$MAKE_DIR"
          make package FINALPACKAGE=1 SYSROOT="" || make FINALPACKAGE=1 SYSROOT="" || make SYSROOT=""
        else
          echo "Makefile bulunamadı!"
          exit 1
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: iOS-Mod-Menu-Output
        path: |
          **/*.dylib
          **/*.deb
          packages/*.deb
